# Item 7 = Comparação de classificações Multinomial e Bernoulli


In [4]:
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score, roc_curve, auc
import matplotlib.pyplot as plt

In [7]:
# De acordo com o proposto no item 7 -> Bernoulli Distribution
X_train = np.array(['Chinese Beijing Chinese', 'Chinese Chinese Shanghai', 'Chinese Macao', 'Tokyo Japan Chinese'])
y_train = np.array(['China','China','China','Not China'])
X_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

vect = CountVectorizer(binary=True)
X_train_dtm = vect.fit_transform(X_train)
print(vect.get_feature_names())
print(X_train_dtm.toarray())

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 1 0 0 0 0]
 [0 1 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]


In [8]:
model = BernoulliNB(binarize=None)
model.fit(X_train_dtm, y_train)

BernoulliNB(alpha=1.0, binarize=None, class_prior=None, fit_prior=True)

In [9]:
X_test_dtm = vect.transform(X_test)
y_pred_class = model.predict(X_test_dtm)
print(X_test_dtm.toarray())

[[0 1 1 0 0 1]]


In [10]:
print(y_pred_class)
# Necessita de referência para a declaração de resultados conforme interações abaixo.

['Not China']


In [11]:
print(((model.predict_proba(X_test_dtm))*100),'%')


[[19.10667888 80.89332112]] %


In [12]:
# De acordo com o proposto no item 7 -> Multinomial Distribution
X_train = np.array(['Chinese Beijing Chinese',
                   'Chinese Chinese Shanghai',
                   'Chinese Macao',
                   'Tokyo Japan Chinese'])
y_train = np.array(['China','China','China','Not China'])
X_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])
vect = CountVectorizer()
X_train_dtm = vect.fit_transform(X_train)
print(vect.get_feature_names())
print(X_train_dtm.toarray())

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 2 0 0 0 0]
 [0 2 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]


In [13]:
model = MultinomialNB()
model.fit(X_train_dtm, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [16]:
X_test_dtm = vect.transform(X_test)
y_pred_class = model.predict(X_test_dtm)
print(X_test_dtm.toarray())
print(y_pred_class)
print(((model.predict_proba(X_test_dtm))*100),'%')
# Resultados

[[0 3 1 0 0 1]]
['China']
[[68.97586118 31.02413882]] %


In [17]:
# Eu entendi e pude observar que: 
# Na iteração [10] podemos observar que um vtest = vtreinamento em "Not China" originando assim...
# ... o resultado encontrado.

# Na iteração [16] "Chinese" é tri existente e de peso/valor maior que as posições negativas.